# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-03 11:45
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок новости')),
                ('small_text', models.CharField(blank=True, default='', max_length=200, verbose_name='Текст новости на главную')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст новости')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата для вывода')),
                ('file', models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
