# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-03 11:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('title', models.CharField(default='', max_length=1000, verbose_name='Название')),
                ('meta_description', models.CharField(blank=True, max_length=1000, verbose_name='Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=1000, verbose_name='Keywords')),
                ('slug', models.SlugField(blank=True, help_text='Только английские буквы, цифры и знаки минус и подчеркивание.', unique=True, verbose_name='Имя для url')),
                ('file', sorl.thumbnail.fields.ImageField(blank=True, upload_to='gallery', verbose_name='Обложка для галереи 250X250')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Раздел галлереи',
                'verbose_name_plural': 'Разделы галлереи',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000, verbose_name='Название')),
                ('file', sorl.thumbnail.fields.ImageField(blank=True, upload_to='gallery', verbose_name='Изображение')),
                ('youtube_url', embed_video.fields.EmbedVideoField(blank=True, verbose_name='Youtube адрес видео')),
                ('num', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Порядковый номер')),
                ('categories', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Category')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['num', 'title'],
            },
        ),
    ]
